package com.cheerself.cheerself.ui.theme

import androidx.compose.ui.graphics.Color

val PrimaryBlue = Color(0xFF346DDD)
val Purple80 = Color(0xFFD0BCFF)
val PurpleGrey80 = Color(0xFFCCC2DC)
val Pink80 = Color(0xFFEFB8C8)

val Purple40 = Color(0xFF6650a4)
val PurpleGrey40 = Color(0xFF625b71)
val Pink40 = Color(0xFF7D5260)

val cheerself_light_primary = Color(0xFF1358C8)
val cheerself_light_onPrimary = Color(0xFFFFFFFF)
val cheerself_light_primaryContainer = Color(0xFFDAE2FF)
val cheerself_light_onPrimaryContainer = Color(0xFF001946)
val cheerself_light_secondary = Color(0xFF585E71)
val cheerself_light_onSecondary = Color(0xFFFFFFFF)
val cheerself_light_secondaryContainer = Color(0xFFDCE2F9)
val cheerself_light_onSecondaryContainer = Color(0xFF151B2C)
val cheerself_light_tertiary = Color(0xFF395BA9)
val cheerself_light_onTertiary = Color(0xFFFFFFFF)
val cheerself_light_tertiaryContainer = Color(0xFFDAE2FF)
val cheerself_light_onTertiaryContainer = Color(0xFF001946)
val cheerself_light_error = Color(0xFFBA1A1A)
val cheerself_light_errorContainer = Color(0xFFFFDAD6)
val cheerself_light_onError = Color(0xFFFFFFFF)
val cheerself_light_onErrorContainer = Color(0xFF410002)
val cheerself_light_background = Color(0xFFFEFBFF)
val cheerself_light_onBackground = Color(0xFF1B1B1F)
val cheerself_light_surface = Color(0xFFFEFBFF)
val cheerself_light_onSurface = Color(0xFF1B1B1F)
val cheerself_light_surfaceVariant = Color(0xFFE1E2EC)
val cheerself_light_onSurfaceVariant = Color(0xFF44464F)
val cheerself_light_outline = Color(0xFF757780)
val cheerself_light_inverseOnSurface = Color(0xFFF2F0F4)
val cheerself_light_inverseSurface = Color(0xFF303034)
val cheerself_light_inversePrimary = Color(0xFFB1C5FF)
val cheerself_light_shadow = Color(0xFF000000)
val cheerself_light_surfaceTint = Color(0xFF1358C8)
val cheerself_light_outlineVariant = Color(0xFFC5C6D0)
val cheerself_light_scrim = Color(0xFF000000)